apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploymnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: honeykwak/argoupdater:2.0
        name: nginx
        ports:
        - containerPort: 80
